# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.daemon = false

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version = b1.7.3
loader_version=0.16.9
mappings = 0.1.1

# Mod Properties
mod_version = 0.4.10+gen2
maven_group = paulevs.bhcreative
archives_base_name = BHCreative

# Dependencies
stapi_version = 2.0.0-alpha.5.4+gen2

# Added by babric2ornithe
biny_mappings = 9859f76
client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
starac_version = 1.2.1+mcb1.7.3+gen2
